POST http://localhost:8080/employees
Content-Type: application/json

{"firstName": "Oluwasayo", "lastName": "Akinkunmi", "email": "oluwasayo.akinkunmi@interswitchng.com"}


###

GET http://localhost:8080/employees/1